import("//build/toolchain/gcc_toolchain.gni")

gcc_toolchain("wasm32") {
  _prefix = rebase_path("$clang_base_path/bin", root_build_dir)

  cc = "${_prefix}/clang"
  cxx = "${_prefix}/clang++"
  ar = "${_prefix}/llvm-ar"
  readelf = "${_prefix}/llvm-readelf"
  nm = "${_prefix}/llvm-nm"
  ld = cxx

  _wasi_stubs = rebase_path("//build/config/wasi/include", root_build_dir)
  extra_cflags = "--target=wasm32-wasip1 --sysroot=${sysroot} -Wno-unknown-warning-option"
  extra_cxxflags = "--target=wasm32-wasip1 --sysroot=${sysroot} -Wno-unknown-warning-option -isystem ${_wasi_stubs}"
  extra_ldflags = "--target=wasm32-wasip1 --sysroot=${sysroot}"

  toolchain_args = {
    current_cpu = "wasm32"
    current_os = "wasi"
    is_clang = true
  }
}
